// SPDX-License-Identifier: GPL-3.0-or-later
package dev.appmatrix.journal;

import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import dev.appmatrix.core.*;
import dev.appmatrix.journal.domain.*;
import java.io.*;
import java.nio.file.*;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.*;

/** Standalone, offline Field Journal. Android framework only; no network permission. */
public final class MainActivity extends Activity {
  private static final int PICK_PHOTO = 101,
      EXPORT_BACKUP = 102,
      RESTORE_BACKUP = 103,
      EXPORT_PHOTO = 104;
  private final ExecutorService io = Executors.newSingleThreadExecutor();
  private final Handler handler = new Handler(Looper.getMainLooper());
  private static JournalStore sessionStore;
  private JournalStore store;
  private JournalStore.State state;
  private DraftStore drafts;
  private DraftStore.Draft draft;
  private LinearLayout root, results;
  private EditText titleInput, bodyInput, tagsInput, searchInput;
  private TextView draftStatus, dateLabel, resultCount;
  private ImageView image;
  private Bitmap photo;
  private boolean busy, editing, loaded;
  private String query = "", tagFilter = "";
  private boolean newestFirst = true;
  private int visibleLimit = 50;
  private final Runnable saveDraftLater = () -> persistDraft(false);
  private JournalStore.Preview pendingRestore;
  private JournalUndoController notesUndo;
  private Button undoButton, redoButton;
  private int pendingResultCode;
  private Uri pendingResultUri;
  private Runnable afterPhotoOpened;

  @Override
  public void onCreate(Bundle saved) {
    Theme.apply(this);
    super.onCreate(saved);
    getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
    drafts = new DraftStore(new File(getFilesDir(), "working-draft"));
    showLoading("Opening your journal…");
    work(
        "Opening private journal",
        () -> {
          synchronized (MainActivity.class) {
            if (sessionStore == null)
              sessionStore =
                  new JournalStore(new File(getFilesDir(), "journal"), MainActivity::validatePhoto);
            store = sessionStore;
          }
          return store.load();
        },
        value -> {
          state = value;
          loaded = true;
          applyRestoredSettings(false);
          showHome();
          if (!resumePendingResult()) checkDraft();
        },
        this::showRecovery);
  }

  static void validatePhoto(File file) throws IOException {
    // Every backed-up image must be a bounded, fully decodable JPEG generated by this app.
    JpegInspector.validate(file);
    BitmapFactory.Options bounds = new BitmapFactory.Options();
    bounds.inJustDecodeBounds = true;
    BitmapFactory.decodeFile(file.getAbsolutePath(), bounds);
    if (bounds.outWidth < 1
        || bounds.outHeight < 1
        || bounds.outWidth > 2048
        || bounds.outHeight > 2048) throw new IOException("Backup photo dimensions are invalid");
    Bitmap decoded = BitmapFactory.decodeFile(file.getAbsolutePath());
    if (decoded == null) throw new IOException("Backup photo is corrupt");
    decoded.recycle();
    try (RandomAccessFile input = new RandomAccessFile(file, "r")) {
      if (input.length() < 4) throw new IOException("Backup photo is truncated");
      input.seek(input.length() - 2);
      if (input.read() != 0xff || input.read() != 0xd9)
        throw new IOException("Backup photo is truncated");
    }
  }

  private void showLoading(String text) {
    LinearLayout box = new LinearLayout(this);
    box.setOrientation(LinearLayout.VERTICAL);
    box.setPadding(dp(24), dp(48), dp(24), dp(24));
    TextView label = label(text, 21);
    box.addView(label);
    box.addView(new ProgressBar(this));
    setContentView(box);
    Theme.style(this, box);
  }

  private void showRecovery(Exception error) {
    showLoading("Your saved journal has been kept");
    new AlertDialog.Builder(this)
        .setTitle("Journal could not be opened")
        .setMessage(
            message(error)
                + "\n\n"
                + "Try recovering a previous complete save, or restore a backup. Nothing will be"
                + " erased automatically.")
        .setPositiveButton(
            "Recover previous",
            (d, w) ->
                work(
                    "Checking previous saves",
                    () -> store.recoverPrevious(),
                    s -> {
                      state = s;
                      loaded = true;
                      applyRestoredSettings(true);
                      showHome();
                      checkDraft();
                    },
                    this::showRecovery))
        .setNeutralButton("Restore backup", (d, w) -> pickRestore())
        .setNegativeButton("Close", (d, w) -> finish())
        .setCancelable(false)
        .show();
  }

  private LinearLayout screen(String heading, String subtitle) {
    root = new LinearLayout(this);
    root.setOrientation(LinearLayout.VERTICAL);
    root.setPadding(dp(18), dp(12), dp(18), dp(12));
    root.setOnApplyWindowInsetsListener(
        (v, insets) -> {
          v.setPadding(
              dp(18) + insets.getSystemWindowInsetLeft(),
              dp(12) + insets.getSystemWindowInsetTop(),
              dp(18) + insets.getSystemWindowInsetRight(),
              dp(12) + insets.getSystemWindowInsetBottom());
          return insets;
        });
    TextView h = label(heading, 29);
    h.setTypeface(null, android.graphics.Typeface.BOLD);
    root.addView(h);
    TextView sub = label(subtitle, 14);
    sub.setTextColor(Theme.muted(this));
    sub.setPadding(0, dp(3), 0, dp(12));
    root.addView(sub);
    Theme.style(this, root);
    setContentView(root);
    root.requestApplyInsets();
    return root;
  }

  private void showHome() {
    handler.removeCallbacks(saveDraftLater);
    disposeUndo();
    editing = false;
    draft = null;
    titleInput = null;
    bodyInput = null;
    tagsInput = null;
    releasePhoto();
    screen("Field Journal", "A private place for what you notice");
    LinearLayout actions = row();
    actions.addView(button("＋ New observation", v -> beginEntry(null)), weight());
    actions.addView(button("More", v -> more()), weight());
    root.addView(actions);
    searchInput = input("Search observations", 1, 160);
    searchInput.setSingleLine(true);
    searchInput.setText(query);
    searchInput.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);
    root.addView(searchInput);
    LinearLayout filters = row();
    Spinner tags = new Spinner(this);
    TreeSet<String> allTags = new TreeSet<>();
    for (Entry e : state.entries) allTags.addAll(e.tags);
    List<String> options = new ArrayList<>();
    options.add("All tags");
    options.addAll(allTags);
    if (!allTags.contains(tagFilter)) tagFilter = "";
    tags.setContentDescription("Filter by tag");
    tags.setAdapter(
        new ArrayAdapter<>(this, android.R.layout.simple_spinner_dropdown_item, options));
    tags.setSelection(tagFilter.isEmpty() ? 0 : options.indexOf(tagFilter));
    filters.addView(tags, weight());
    Spinner order = new Spinner(this);
    order.setContentDescription("Chronological order");
    order.setAdapter(
        new ArrayAdapter<>(
            this,
            android.R.layout.simple_spinner_dropdown_item,
            new String[] {"Newest first", "Oldest first"}));
    order.setSelection(newestFirst ? 0 : 1);
    filters.addView(order, weight());
    root.addView(filters);
    resultCount = label("", 13);
    resultCount.setTextColor(Theme.muted(this));
    resultCount.setPadding(0, dp(8), 0, dp(8));
    root.addView(resultCount);
    ScrollView scroll = new ScrollView(this);
    scroll.setFillViewport(true);
    results = new LinearLayout(this);
    results.setOrientation(LinearLayout.VERTICAL);
    scroll.addView(results);
    root.addView(scroll, new LinearLayout.LayoutParams(-1, 0, 1));
    searchInput.addTextChangedListener(
        watcher(
            () -> {
              query = searchInput.getText().toString();
              visibleLimit = 50;
              renderResults();
            }));
    tags.setOnItemSelectedListener(
        selected(
            pos -> {
              tagFilter = pos == 0 ? "" : options.get(pos);
              visibleLimit = 50;
              renderResults();
            }));
    order.setOnItemSelectedListener(
        selected(
            pos -> {
              newestFirst = pos == 0;
              renderResults();
            }));
    renderResults();
  }

  private void renderResults() {
    if (editing || results == null || state == null) return;
    results.removeAllViews();
    List<Entry> matches = Entry.filter(state.entries, query, tagFilter, newestFirst);
    resultCount.setText(
        matches.size()
            + " observation"
            + (matches.size() == 1 ? "" : "s")
            + (state.entries.size() != matches.size()
                ? " · " + state.entries.size() + " total"
                : "")
            + " · On this device");
    if (matches.isEmpty()) {
      LinearLayout empty = card();
      TextView heading =
          label(state.entries.isEmpty() ? "Start with a moment" : "No matching observations", 22);
      empty.addView(heading);
      empty.addView(
          label(
              state.entries.isEmpty()
                  ? "A bird on your walk, an idea, a changing sky. Add a date, a few words and, if"
                      + " you like, a photo. Everything stays on this device until you export it."
                  : "Try another phrase, a date such as 2026-10, or choose All tags.",
              16));
      if (state.entries.isEmpty())
        empty.addView(button("Create your first observation", v -> beginEntry(null)));
      else
        empty.addView(
            button(
                "Clear search and filters",
                v -> {
                  query = "";
                  tagFilter = "";
                  showHome();
                }));
      results.addView(empty);
      return;
    }
    for (int index = 0; index < Math.min(matches.size(), visibleLimit); index++) {
      Entry e = matches.get(index);
      LinearLayout item = card();
      TextView date = label(e.date + (e.source.isEmpty() ? " · Note" : " · Photo observation"), 13);
      date.setTextColor(Theme.accent(this));
      item.addView(date);
      TextView title = label(e.title, 20);
      title.setTypeface(null, android.graphics.Typeface.BOLD);
      item.addView(title);
      if (!e.body.isEmpty()) {
        TextView body = label(e.body, 15);
        body.setMaxLines(3);
        body.setEllipsize(TextUtils.TruncateAt.END);
        item.addView(body);
      }
      if (!e.tags.isEmpty()) {
        TextView t = label(String.join("  ·  ", e.tags), 13);
        t.setTextColor(Theme.muted(this));
        item.addView(t);
      }
      item.setFocusable(true);
      item.setClickable(true);
      item.setContentDescription("Open " + e.title + ", " + e.date);
      item.setOnClickListener(v -> beginEntry(e));
      item.setForeground(getDrawable(android.R.drawable.list_selector_background));
      results.addView(item);
    }
    if (matches.size() > visibleLimit)
      results.addView(
          button(
              "Show 50 more",
              v -> {
                visibleLimit += 50;
                renderResults();
              }));
  }

  private void more() {
    new AlertDialog.Builder(this)
        .setTitle("Your journal")
        .setItems(
            new String[] {
              "Export backup", "Restore backup", "Settings", "About & open-source licenses"
            },
            (dialog, which) -> {
              if (which == 0) requestBackup();
              else if (which == 1) pickRestore();
              else if (which == 2) journalSettings();
              else About.show(this);
            })
        .setNegativeButton("Close", null)
        .show();
  }

  private void journalSettings() {
    new AlertDialog.Builder(this)
        .setTitle("Settings")
        .setItems(
            new String[] {
              "Appearance & privacy",
              "Photo export quality: " + Settings.readExportQuality(this) + "%"
            },
            (dialog, which) -> {
              if (which == 0) Settings.show(this, this::saveSettings);
              else {
                int[] values = {80, 90, 100};
                int current = Settings.readExportQuality(this);
                int[] chosen = {current};
                new AlertDialog.Builder(this)
                    .setTitle("Photo export quality")
                    .setSingleChoiceItems(
                        new String[] {
                          "80% · smaller files", "90% · balanced", "100% · highest quality"
                        },
                        current == 80 ? 0 : current == 100 ? 2 : 1,
                        (d, index) -> chosen[0] = values[index])
                    .setPositiveButton(
                        "Save",
                        (d, w) -> {
                          try {
                            Settings.writeExportQuality(this, chosen[0]);
                            saveSettings();
                          } catch (RuntimeException error) {
                            error(error);
                          }
                        })
                    .setNegativeButton("Cancel", null)
                    .show();
              }
            })
        .setNegativeButton("Close", null)
        .show();
  }

  private void beginEntry(Entry entry) {
    if (busy) return;
    try {
      DraftStore.Draft pending = drafts.load();
      if (pending != null && !pending.journalId.equals(state.journalId)) {
        drafts.discard();
        pending = null;
      }
      final DraftStore.Draft resumable = pending;
      if (resumable != null && resumable.dirty) {
        new AlertDialog.Builder(this)
            .setTitle("You have a saved draft")
            .setMessage("Continue it, or explicitly discard it before opening another observation.")
            .setPositiveButton(
                "Resume draft",
                (d, w) -> {
                  draft = resumable;
                  showEditor();
                })
            .setNegativeButton("Keep draft", null)
            .setNeutralButton(
                "Discard draft",
                (d, w) ->
                    new AlertDialog.Builder(this)
                        .setTitle("Discard saved draft?")
                        .setMessage("This removes only the unsaved draft.")
                        .setPositiveButton(
                            "Discard",
                            (a, b) -> {
                              drafts.discard();
                              beginEntry(entry);
                            })
                        .setNegativeButton("Cancel", null)
                        .show())
            .show();
        return;
      }
    } catch (IOException e) {
      error(
          new IOException(
              "A draft needs recovery. Reopen the app to recover or explicitly discard it.", e));
      return;
    }
    hideKeyboard();
    work(
        "Preparing observation",
        () -> drafts.begin(entry, state),
        d -> {
          draft = d;
          showEditor();
        },
        this::error);
  }

  private void checkDraft() {
    try {
      DraftStore.Draft found = drafts.load();
      if (found == null) return;
      if (!found.journalId.equals(state.journalId)) {
        drafts.discard();
        toast("An earlier draft was removed after journal restoration");
        return;
      }
      if (!found.dirty) {
        drafts.discard();
        return;
      }
      new AlertDialog.Builder(this)
          .setTitle("Continue your draft?")
          .setMessage(
              (found.title.isEmpty() ? "Untitled observation" : found.title)
                  + "\n"
                  + found.date
                  + "\n\nYour unsaved changes were kept on this device.")
          .setPositiveButton(
              "Continue editing",
              (d, w) -> {
                draft = found;
                showEditor();
              })
          .setNegativeButton(
              "Discard draft",
              (d, w) ->
                  new AlertDialog.Builder(this)
                      .setTitle("Discard saved draft?")
                      .setMessage(
                          "Only this unsaved draft will be removed. Saved observations are"
                              + " unchanged.")
                      .setPositiveButton("Discard", (a, b) -> drafts.discard())
                      .setNegativeButton("Keep draft", (a, b) -> checkDraft())
                      .setOnCancelListener(a -> checkDraft())
                      .show())
          .setCancelable(false)
          .show();
    } catch (IOException e) {
      new AlertDialog.Builder(this)
          .setTitle("Draft could not be recovered")
          .setMessage(message(e) + "\nYour saved observations are unchanged.")
          .setPositiveButton("Keep draft", null)
          .setNegativeButton("Discard broken draft", (d, w) -> drafts.discard())
          .show();
    }
  }

  private void showEditor() {
    disposeUndo();
    editing = true;
    screen(
        draft.existing ? "Edit observation" : "New observation",
        "Draft saved locally as you write");
    LinearLayout nav = row();
    nav.addView(button("Back", v -> leaveEditor()), weight());
    nav.addView(button("Save observation", v -> saveEntry()), weight());
    root.addView(nav);
    ScrollView scroll = new ScrollView(this);
    LinearLayout form = new LinearLayout(this);
    form.setOrientation(LinearLayout.VERTICAL);
    scroll.addView(form);
    root.addView(scroll, new LinearLayout.LayoutParams(-1, 0, 1));
    form.addView(label("TITLE", 12));
    titleInput = input("Give this moment a title", 1, 160);
    titleInput.setText(draft.title);
    form.addView(titleInput);
    LinearLayout dateRow = row();
    dateLabel = label(draft.date, 18);
    dateLabel.setGravity(Gravity.CENTER_VERTICAL);
    dateRow.addView(dateLabel, weight());
    dateRow.addView(button("Change date", v -> changeDate()), weight());
    form.addView(dateRow);
    form.addView(label("NOTES", 12));
    bodyInput = input("What did you notice?", 5, 50000);
    bodyInput.setText(draft.body);
    bodyInput.setGravity(Gravity.TOP);
    bodyInput.setInputType(
        android.text.InputType.TYPE_CLASS_TEXT
            | android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE
            | android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);
    form.addView(bodyInput, new LinearLayout.LayoutParams(-1, dp(180)));
    LinearLayout history = row();
    undoButton =
        button(
            "Undo notes",
            v -> {
              if (notesUndo != null) notesUndo.undo();
            });
    redoButton =
        button(
            "Redo notes",
            v -> {
              if (notesUndo != null) notesUndo.redo();
            });
    history.addView(undoButton, weight());
    history.addView(redoButton, weight());
    form.addView(history);
    notesUndo = new JournalUndoController(bodyInput, this::refreshUndo);
    refreshUndo();
    form.addView(label("TAGS", 12));
    tagsInput = input("e.g. birds, trail, ideas", 1, 680);
    tagsInput.setText(draft.tags);
    form.addView(tagsInput);
    form.addView(label("Separate tags with commas · up to 20", 12));
    image = new ImageView(this);
    image.setScaleType(ImageView.ScaleType.FIT_CENTER);
    image.setAdjustViewBounds(true);
    image.setContentDescription("Current observation photo");
    form.addView(image, new LinearLayout.LayoutParams(-1, dp(220)));
    LinearLayout photoRow = row();
    photoRow.addView(
        button(draft.source.isEmpty() ? "Add photo" : "Replace photo", v -> pickPhoto()), weight());
    photoRow.addView(button("Photo tools", v -> photoTools()), weight());
    form.addView(photoRow);
    TextView privacy =
        label(
            "Photos are copied into private storage. Your gallery originals stay untouched. Photo"
                + " tools keep the imported source so you can reset later.",
            13);
    privacy.setTextColor(Theme.muted(this));
    form.addView(privacy);
    draftStatus =
        label(draft.dirty ? "Unsaved changes · draft kept locally" : "No unsaved changes", 13);
    draftStatus.setPadding(0, dp(16), 0, dp(16));
    form.addView(draftStatus);
    if (draft.existing) form.addView(button("Delete observation", v -> deleteEntry()));
    titleInput.addTextChangedListener(watcher(this::onEdited));
    bodyInput.addTextChangedListener(watcher(this::onEdited));
    tagsInput.addTextChangedListener(watcher(this::onEdited));
    refreshPhoto();
  }

  private void refreshUndo() {
    if (undoButton != null) undoButton.setEnabled(notesUndo != null && notesUndo.canUndo());
    if (redoButton != null) redoButton.setEnabled(notesUndo != null && notesUndo.canRedo());
  }

  private void disposeUndo() {
    if (notesUndo != null) {
      notesUndo.dispose();
      notesUndo = null;
    }
    undoButton = null;
    redoButton = null;
  }

  private void onEdited() {
    if (!editing || draft == null) return;
    captureFields();
    draft.dirty = true;
    if (draftStatus != null) draftStatus.setText("Unsaved changes · saving draft…");
    handler.removeCallbacks(saveDraftLater);
    handler.postDelayed(saveDraftLater, 350);
  }

  private void captureFields() {
    if (draft != null && titleInput != null) {
      draft.title = titleInput.getText().toString();
      draft.body = bodyInput.getText().toString();
      draft.tags = tagsInput.getText().toString();
    }
  }

  private boolean persistDraft(boolean report) {
    if (!editing || draft == null) return true;
    handler.removeCallbacks(saveDraftLater);
    captureFields();
    try {
      drafts.save(draft);
      if (draftStatus != null)
        draftStatus.setText(
            draft.dirty ? "Unsaved changes · draft kept locally" : "No unsaved changes");
      return true;
    } catch (IOException e) {
      if (draftStatus != null)
        draftStatus.setText("Draft could not be saved. Keep this screen open and try Save.");
      if (report) error(e);
      return false;
    }
  }

  private void changeDate() {
    LocalDate date;
    try {
      date = LocalDate.parse(draft.date);
    } catch (Exception e) {
      date = LocalDate.now();
    }
    new DatePickerDialog(
            this,
            (v, y, m, d) -> {
              draft.date = LocalDate.of(y, m + 1, d).toString();
              dateLabel.setText(draft.date);
              onEdited();
            },
            date.getYear(),
            date.getMonthValue() - 1,
            date.getDayOfMonth())
        .show();
  }

  private void saveEntry() {
    if (busy || draft == null) return;
    captureFields();
    final Entry entry;
    try {
      entry = draft.entry();
    } catch (IOException e) {
      error(e);
      return;
    }
    persistDraft(false);
    hideKeyboard();
    List<Entry> entries = new ArrayList<>(state.entries);
    entries.removeIf(e -> e.id.equals(entry.id));
    entries.add(entry);
    work(
        "Saving observation",
        () -> {
          Map<String, File> files = JournalStore.mediaMap(state);
          if (!entry.source.isEmpty()) {
            files.put(entry.source, drafts.media(entry.source));
            files.put(entry.rendered, drafts.media(entry.rendered));
          }
          return store.save(
              entries, Settings.readTheme(this), Settings.readExportQuality(this), files);
        },
        s -> {
          state = s;
          drafts.discard();
          showHome();
          toast("Observation saved");
        },
        this::error);
  }

  private void leaveEditor() {
    if (busy) return;
    captureFields();
    if (draft == null || !draft.dirty) {
      drafts.discard();
      showHome();
      return;
    }
    new AlertDialog.Builder(this)
        .setTitle("Keep this draft?")
        .setMessage("This observation has unsaved changes.")
        .setPositiveButton("Save observation", (d, w) -> saveEntry())
        .setNeutralButton(
            "Keep draft & close",
            (d, w) -> {
              if (persistDraft(true)) {
                showHome();
                checkDraftBanner();
              }
            })
        .setNegativeButton(
            "Discard changes",
            (d, w) ->
                new AlertDialog.Builder(this)
                    .setTitle("Discard unsaved changes?")
                    .setMessage("Saved observations and source photos are unchanged.")
                    .setPositiveButton(
                        "Discard",
                        (a, b) -> {
                          handler.removeCallbacks(saveDraftLater);
                          drafts.discard();
                          showHome();
                        })
                    .setNegativeButton("Keep editing", null)
                    .show())
        .show();
  }

  private void checkDraftBanner() {
    Button resume = button("Resume saved draft", v -> checkDraft());
    root.addView(resume, 2);
    // Starting a different observation must never silently overwrite this draft.
  }

  private void deleteEntry() {
    new AlertDialog.Builder(this)
        .setTitle("Delete this observation?")
        .setMessage(
            "“"
                + draft.title
                + "” and its private photo copies will be removed from the current journal. Other"
                + " observations are unchanged. A previously exported backup may still contain this"
                + " entry.")
        .setPositiveButton(
            "Delete observation",
            (dialog, w) -> {
              List<Entry> remaining = new ArrayList<>(state.entries);
              remaining.removeIf(e -> e.id.equals(draft.id));
              work(
                  "Deleting observation",
                  () ->
                      store.save(
                          remaining,
                          Settings.readTheme(this),
                          Settings.readExportQuality(this),
                          JournalStore.mediaMap(state)),
                  s -> {
                    state = s;
                    handler.removeCallbacks(saveDraftLater);
                    drafts.discard();
                    showHome();
                    toast("Observation deleted");
                  },
                  this::error);
            })
        .setNegativeButton("Cancel", null)
        .show();
  }

  private void pickPhoto() {
    if (!persistDraft(true)) return;
    Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
    intent.addCategory(Intent.CATEGORY_OPENABLE);
    intent.setType("image/*");
    launch(intent, PICK_PHOTO);
  }

  private void photoTools() {
    if (draft.source.isEmpty()) {
      toast("Add a photo first");
      return;
    }
    new AlertDialog.Builder(this)
        .setTitle("Photo tools")
        .setItems(
            new String[] {
              "Adjust light & color curves",
              "Rotate clockwise",
              "Reset to imported source",
              "Export current photo",
              "Remove photo"
            },
            (d, w) -> {
              if (w == 0) {
                if (photo != null)
                  PhotoAdjustments.edit(this, photo, bitmap -> savePhotoRevision(bitmap));
              } else if (w == 1) {
                if (photo != null)
                  work(
                      "Rotating photo",
                      () -> BitmapTransforms.rotate(photo, 1),
                      this::savePhotoRevision,
                      this::error);
              } else if (w == 2)
                new AlertDialog.Builder(this)
                    .setTitle("Reset photo edits?")
                    .setMessage("The imported source will replace your current edited photo.")
                    .setPositiveButton(
                        "Reset",
                        (a, b) -> {
                          draft.rendered = draft.source;
                          draft.dirty = true;
                          persistDraft(true);
                          refreshPhoto();
                        })
                    .setNegativeButton("Cancel", null)
                    .show();
              else if (w == 3) {
                Intent i = new Intent(Intent.ACTION_CREATE_DOCUMENT);
                i.addCategory(Intent.CATEGORY_OPENABLE);
                i.setType("image/jpeg");
                i.putExtra(Intent.EXTRA_TITLE, "field-journal-" + draft.date + ".jpg");
                launch(i, EXPORT_PHOTO);
              } else
                new AlertDialog.Builder(this)
                    .setTitle("Remove this photo?")
                    .setMessage(
                        "The observation text will stay. Your gallery original is unchanged.")
                    .setPositiveButton(
                        "Remove photo",
                        (a, b) -> {
                          draft.source = "";
                          draft.rendered = "";
                          draft.dirty = true;
                          persistDraft(true);
                          refreshPhoto();
                        })
                    .setNegativeButton("Cancel", null)
                    .show();
            })
        .setNegativeButton("Cancel", null)
        .show();
  }

  private String writeDraftPhoto(Bitmap bitmap) throws IOException {
    String name = UUID.randomUUID() + ".jpg";
    File target = drafts.media(name);
    File temp = new File(target.getParentFile(), name + ".tmp");
    try (FileOutputStream output = new FileOutputStream(temp)) {
      BitmapTransforms.exportJpeg(bitmap, output, 90);
      output.getFD().sync();
    } catch (IOException | RuntimeException e) {
      temp.delete();
      throw e;
    }
    Files.move(
        temp.toPath(),
        target.toPath(),
        StandardCopyOption.ATOMIC_MOVE,
        StandardCopyOption.REPLACE_EXISTING);
    validatePhoto(target);
    return name;
  }

  private void savePhotoRevision(Bitmap bitmap) {
    work(
        "Saving photo adjustment",
        () -> writeDraftPhoto(bitmap),
        name -> {
          draft.rendered = name;
          draft.dirty = true;
          persistDraft(true);
          refreshPhoto();
          if (bitmap != photo && !bitmap.isRecycled()) bitmap.recycle();
        },
        e -> {
          if (bitmap != photo && !bitmap.isRecycled()) bitmap.recycle();
          error(e);
        });
  }

  private void refreshPhoto() {
    releasePhoto();
    if (image == null) return;
    if (draft == null || draft.rendered.isEmpty()) {
      image.setImageDrawable(null);
      image.setVisibility(View.GONE);
      runAfterPhotoOpened();
      return;
    }
    image.setVisibility(View.VISIBLE);
    work(
        "Opening photo",
        () -> MediaFiles.loadBitmap(drafts.media(draft.rendered).getAbsolutePath()),
        bitmap -> {
          photo = bitmap;
          image.setImageBitmap(bitmap);
          runAfterPhotoOpened();
        },
        e -> {
          image.setImageDrawable(null);
          error(e);
          runAfterPhotoOpened();
        });
  }

  private void runAfterPhotoOpened() {
    if (afterPhotoOpened != null) {
      Runnable next = afterPhotoOpened;
      afterPhotoOpened = null;
      next.run();
    }
  }

  private boolean resumePendingResult() {
    if (pendingResultUri == null) return false;
    int code = pendingResultCode;
    Uri uri = pendingResultUri;
    pendingResultUri = null;
    if (code == PICK_PHOTO || code == EXPORT_PHOTO) {
      try {
        DraftStore.Draft saved = drafts.load();
        if (saved == null || !saved.journalId.equals(state.journalId)) {
          error(
              new IOException(
                  "The photo picker returned after the draft was closed. Open an observation and"
                      + " choose the photo again."));
          return true;
        }
        draft = saved;
        afterPhotoOpened = () -> handleDocumentResult(code, uri);
        showEditor();
        return true;
      } catch (IOException error) {
        error(error);
        return true;
      }
    }
    handleDocumentResult(code, uri);
    return true;
  }

  private void releasePhoto() {
    if (image != null) image.setImageDrawable(null);
    if (photo != null && !photo.isRecycled()) photo.recycle();
    photo = null;
  }

  private void requestBackup() {
    new AlertDialog.Builder(this)
        .setTitle("Export a private backup")
        .setMessage(
            "The .fjbackup archive includes all saved observations, notes, dates, tags, original"
                + " imported photos, edited photos and settings. It is NOT encrypted. Anyone with"
                + " the file can read it. Unsaved drafts are not included.\n\n"
                + "Choose a trusted destination; a cloud document provider may upload the file.")
        .setPositiveButton(
            "Choose destination",
            (d, w) -> {
              Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
              intent.addCategory(Intent.CATEGORY_OPENABLE);
              intent.setType("application/zip");
              intent.putExtra(Intent.EXTRA_TITLE, "field-journal-" + LocalDate.now() + ".fjbackup");
              launch(intent, EXPORT_BACKUP);
            })
        .setNegativeButton("Cancel", null)
        .show();
  }

  private void pickRestore() {
    Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
    intent.addCategory(Intent.CATEGORY_OPENABLE);
    intent.setType("*/*");
    launch(intent, RESTORE_BACKUP);
  }

  private void previewRestore(Uri uri) {
    work(
        "Checking backup safely",
        () -> {
          try (InputStream input = getContentResolver().openInputStream(uri)) {
            if (input == null) throw new IOException("Cannot read this backup");
            return store.previewRestore(input);
          }
        },
        preview -> {
          pendingRestore = preview;
          int count = preview.state.entries.size(), photos = preview.state.photoCount();
          String current =
              state == null
                  ? "the existing journal"
                  : state.entries.size() + " currently saved observations";
          AlertDialog dialog =
              new AlertDialog.Builder(this)
                  .setTitle("Replace journal with this backup?")
                  .setMessage(
                      "Validated backup version 1\n"
                          + count
                          + " observations · "
                          + photos
                          + " with photos\nTheme: "
                          + preview.state.theme
                          + "\n\nThis replaces "
                          + current
                          + " and saved settings. Any unsaved draft is also discarded after you"
                          + " confirm. It does not merge. The prior complete save is kept privately"
                          + " for recovery. Export a backup first if you want a separate copy.")
                  .setPositiveButton(
                      "Replace journal",
                      (d, w) ->
                          work(
                              "Restoring journal",
                              () -> store.activate(preview),
                              s -> {
                                pendingRestore = null;
                                state = s;
                                loaded = true;
                                drafts.discard();
                                applyRestoredSettings(true);
                                showHome();
                                toast("Restored " + s.entries.size() + " observations");
                              },
                              e -> {
                                store.cancel(preview);
                                pendingRestore = null;
                                error(e);
                              }))
                  .setNegativeButton(
                      "Cancel",
                      (d, w) -> {
                        store.cancel(preview);
                        pendingRestore = null;
                      })
                  .create();
          dialog.setOnCancelListener(
              d -> {
                store.cancel(preview);
                pendingRestore = null;
              });
          dialog.show();
        },
        this::error);
  }

  private void saveSettings() {
    if (state == null) return;
    work(
        "Saving settings",
        () ->
            store.save(
                state.entries,
                Settings.readTheme(this),
                Settings.readExportQuality(this),
                JournalStore.mediaMap(state)),
        s -> {
          state = s;
          recreate();
        },
        this::error);
  }

  private void applyRestoredSettings(boolean report) {
    try {
      Settings.writeTheme(this, state.theme);
      Settings.writeExportQuality(this, state.quality);
      Theme.apply(this);
    } catch (RuntimeException e) {
      if (report)
        error(
            new IOException(
                "Journal restored, but appearance settings could not be applied. Reopen Settings to"
                    + " retry.",
                e));
    }
  }

  private void launch(Intent intent, int code) {
    if (busy) return;
    try {
      startActivityForResult(intent, code);
    } catch (ActivityNotFoundException e) {
      error(new IOException("No system document picker is available on this device", e));
    }
  }

  @Override
  protected void onActivityResult(int request, int result, Intent data) {
    super.onActivityResult(request, result, data);
    if (result != RESULT_OK || data == null || data.getData() == null) return;
    Uri uri = data.getData();
    if (!isDocumentUri(uri)) {
      error(
          new IOException(
              "Choose a file through a trusted system document provider. This picker returned an"
                  + " unsupported location."));
      return;
    }
    if (!loaded || ((request == PICK_PHOTO || request == EXPORT_PHOTO) && !editing)) {
      pendingResultCode = request;
      pendingResultUri = uri;
      if (loaded) resumePendingResult();
      return;
    }
    handleDocumentResult(request, uri);
  }

  static boolean isDocumentUri(Uri uri) {
    return uri != null
        && ContentResolver.SCHEME_CONTENT.equals(uri.getScheme())
        && !TextUtils.isEmpty(uri.getAuthority());
  }

  private void handleDocumentResult(int request, Uri uri) {
    if (!isDocumentUri(uri)) {
      error(new IOException("Choose a file through the Android system picker"));
      return;
    }
    if (request == PICK_PHOTO && editing && draft != null) {
      work(
          "Importing private photo copy",
          () -> {
            Bitmap bitmap = MediaFiles.readBitmap(this, uri, 2048);
            try {
              return writeDraftPhoto(bitmap);
            } finally {
              bitmap.recycle();
            }
          },
          name -> {
            draft.source = name;
            draft.rendered = name;
            draft.dirty = true;
            persistDraft(true);
            refreshPhoto();
          },
          this::error);
    } else if (request == EXPORT_BACKUP && state != null) {
      work(
          "Writing backup",
          () -> {
            try (OutputStream output = getContentResolver().openOutputStream(uri, "wt")) {
              if (output == null) throw new IOException("Cannot write to this destination");
              store.exportBackup(state, output);
            }
            return true;
          },
          ok -> toast("Backup exported. Keep it somewhere safe."),
          e ->
              error(
                  new IOException(
                      "Backup export failed. The destination may contain an incomplete file; remove"
                          + " it and try again. Your journal is unchanged.\n"
                          + message(e),
                      e)));
    } else if (request == RESTORE_BACKUP) {
      previewRestore(uri);
    } else if (request == EXPORT_PHOTO && editing && draft != null) {
      work(
          "Exporting photo",
          () -> {
            Bitmap bitmap = MediaFiles.loadBitmap(drafts.media(draft.rendered).getAbsolutePath());
            try {
              MediaFiles.copyTo(this, uri, bitmap, Settings.readExportQuality(this));
            } finally {
              bitmap.recycle();
            }
            return true;
          },
          ok -> toast("Photo exported"),
          e ->
              error(
                  new IOException(
                      "Photo export failed; the destination may contain an incomplete file. Your"
                          + " observation is unchanged.\n"
                          + message(e),
                      e)));
    }
  }

  @Override
  public void onBackPressed() {
    if (busy) {
      toast("Please wait for the current operation");
      return;
    }
    if (editing) leaveEditor();
    else super.onBackPressed();
  }

  @Override
  protected void onPause() {
    persistDraft(false);
    super.onPause();
  }

  @Override
  protected void onSaveInstanceState(Bundle out) {
    persistDraft(false);
    super.onSaveInstanceState(out);
  }

  @Override
  protected void onDestroy() {
    handler.removeCallbacks(saveDraftLater);
    disposeUndo();
    if (pendingRestore != null && store != null) store.cancel(pendingRestore);
    io.shutdown();
    super.onDestroy();
  }

  private interface Job<T> {
    T run() throws Exception;
  }

  private interface Success<T> {
    void accept(T value);
  }

  private interface Failure {
    void accept(Exception error);
  }

  private <T> void work(String label, Job<T> job, Success<T> success, Failure failure) {
    if (busy) return;
    busy = true;
    ProgressDialog progress = new ProgressDialog(this);
    progress.setMessage(label + "…");
    progress.setIndeterminate(true);
    progress.setCancelable(false);
    progress.show();
    io.execute(
        () -> {
          try {
            T value = job.run();
            runOnUiThread(
                () -> {
                  busy = false;
                  if (!isDestroyed()) {
                    progress.dismiss();
                    success.accept(value);
                  }
                });
          } catch (Exception e) {
            runOnUiThread(
                () -> {
                  busy = false;
                  if (!isDestroyed()) {
                    progress.dismiss();
                    failure.accept(e);
                  }
                });
          } catch (OutOfMemoryError e) {
            runOnUiThread(
                () -> {
                  busy = false;
                  if (!isDestroyed()) {
                    progress.dismiss();
                    failure.accept(
                        new IOException(
                            "This operation needs more memory. Try a smaller photo or backup."));
                  }
                });
          }
        });
  }

  private TextView label(String text, int sp) {
    TextView view = new TextView(this);
    view.setText(text);
    view.setTextSize(sp);
    view.setTextColor(Theme.text(this));
    view.setPadding(0, dp(4), 0, dp(4));
    return view;
  }

  private EditText input(String hint, int lines, int max) {
    EditText view = new EditText(this);
    view.setHint(hint);
    view.setContentDescription(hint);
    view.setTextSize(17);
    view.setTextColor(Theme.text(this));
    view.setHintTextColor(Theme.muted(this));
    view.setMinLines(lines);
    view.setFilters(new InputFilter[] {new InputFilter.LengthFilter(max)});
    view.setSingleLine(lines == 1);
    view.setSelectAllOnFocus(false);
    return view;
  }

  private Button button(String text, View.OnClickListener listener) {
    Button button = new Button(this);
    button.setText(text);
    button.setAllCaps(false);
    button.setMinHeight(dp(48));
    button.setOnClickListener(listener);
    return button;
  }

  private LinearLayout row() {
    LinearLayout row = new LinearLayout(this);
    row.setOrientation(LinearLayout.HORIZONTAL);
    return row;
  }

  private LinearLayout.LayoutParams weight() {
    return new LinearLayout.LayoutParams(0, -2, 1);
  }

  private LinearLayout card() {
    LinearLayout box = new LinearLayout(this);
    box.setOrientation(LinearLayout.VERTICAL);
    box.setPadding(dp(16), dp(14), dp(16), dp(14));
    box.setBackground(Theme.card(this));
    LinearLayout.LayoutParams p = new LinearLayout.LayoutParams(-1, -2);
    p.setMargins(0, 0, 0, dp(12));
    box.setLayoutParams(p);
    return box;
  }

  private TextWatcher watcher(Runnable changed) {
    return new TextWatcher() {
      public void beforeTextChanged(CharSequence s, int st, int count, int after) {}

      public void onTextChanged(CharSequence s, int start, int before, int count) {
        changed.run();
      }

      public void afterTextChanged(Editable e) {}
    };
  }

  private interface Position {
    void accept(int index);
  }

  private AdapterView.OnItemSelectedListener selected(Position action) {
    return new AdapterView.OnItemSelectedListener() {
      public void onItemSelected(AdapterView<?> a, View v, int p, long id) {
        action.accept(p);
      }

      public void onNothingSelected(AdapterView<?> a) {}
    };
  }

  private int dp(int value) {
    return Theme.dp(this, value);
  }

  private void hideKeyboard() {
    View focus = getCurrentFocus();
    if (focus != null)
      ((InputMethodManager) getSystemService(INPUT_METHOD_SERVICE))
          .hideSoftInputFromWindow(focus.getWindowToken(), 0);
  }

  private void toast(String text) {
    Toast.makeText(this, text, Toast.LENGTH_LONG).show();
  }

  private String message(Exception error) {
    return error.getMessage() == null
        ? "Please try again. Your saved journal has been kept."
        : error.getMessage();
  }

  private void error(Exception error) {
    new AlertDialog.Builder(this)
        .setTitle("Couldn't complete that")
        .setMessage(message(error))
        .setPositiveButton("OK", null)
        .show();
  }
}
